In [6]:
#1.Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

##Ans..Here are three different methods for creating identical 2D arrays in NumPy:

Method 1: Using numpy.array()


import numpy as np

# Create a 2D array using numpy.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print(array1)


Output:


[[1 2 3]
 [4 5 6]]


Method 2: Using numpy.zeros() and assignment


import numpy as np

# Create a 2D array filled with zeros
array2 = np.zeros((2, 3))

# Assign values to the array
array2[0, :] = [1, 2, 3]
array2[1, :] = [4, 5, 6]

print(array2)


Output:


[[1. 2. 3.]
 [4. 5. 6.]]


Method 3: Using numpy.full()


import numpy as np

# Create a 2D array filled with a specified value
array3 = np.full((2, 3), 0)

# Assign values to the array
array3[:] = [[1, 2, 3], [4, 5, 6]]

print(array3)


Output:


[[1 2 3]
 [4 5 6]]


All three methods produce identical 2D arrays. Note that in Method 2 and Method 3, the arrays are initially filled with zeros, and then assigned the desired values.



In [2]:
#2.Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and reshape that 1D array into a 2D array.

##Ans.Here's how you can generate an array of 100 evenly spaced numbers between 1 and 10 and reshape it into a 2D array using NumPy:


import numpy as np

# Generate an array of 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array with 10 rows and 10 columns
array_2d = array_1d.reshape(10, 10)

print(array_2d)


#In this code:

# - np.linspace(1, 10, 100) generates an array of 100 evenly spaced numbers between 1 and 10.
# - array_1d.reshape(10, 10) reshapes the 1D array into a 2D array with 10 rows and 10 columns.

# The output will be a 2D array with 10 rows and 10 columns, where each element is an evenly spaced number between 1 and 10.

[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

In [ ]:
#3.Explain the following terms:
The difference in np.array, np.asarray and np.asanyarray.
The difference between Deep copy and shallow copy

##Ans.The main differences between np.array, np.asarray, and np.asanyarray are:

1. Data Copying:
    - np.array always creates a new copy of the input data.
    - np.asarray creates a new copy only if necessary (e.g., if the input is a list or a non-Numpy array). If the input is already a Numpy array, it returns the original array without copying.
    - np.asanyarray is similar to np.asarray, but it also allows non-Numpy arrays (like scipy.sparse matrices) to pass through unchanged.
2. Input Validation:
    - np.array checks the input data for validity and raises an error if it's not a valid array-like object.
    - np.asarray and np.asanyarray are more lenient and don't raise errors for invalid inputs. Instead, they try to convert the input to an array.
3. Output Type:
    - np.array always returns a Numpy ndarray.
    - np.asarray returns a Numpy ndarray or a subclass of it (like a numpy.memmap object).
    - np.asanyarray returns a Numpy ndarray or any other type of array-like object (like a scipy.sparse matrix).

In summary:

- Use np.array when you want to ensure a new copy of the data is created and you need strict input validation.
- Use np.asarray when you want to convert an array-like object to a Numpy array without copying if possible.
- Use np.asanyarray when you want to allow non-Numpy arrays to pass through unchanged and don't need strict input validation.

#In programming, a copy of an object can be either a deep copy or a shallow copy.

Shallow Copy:
A shallow copy of an object creates a new object and then (to the extent possible) inserts references to the original elements into it. This means that:

- The new object is a separate entity from the original object.
- However, the elements of the new object are the same as the elements of the original object (i.e., they are referenced, not copied).

Example:

import copy

original_list = [[1, 2], [3, 4]]
shallow_copied_list = copy.copy(original_list)

# Modify the original list
original_list[0][0] = 'X'

print(original_list)  # Output: [['X', 2], [3, 4]]
print(shallow_copied_list)  # Output: [['X', 2], [3, 4]]

As you can see, modifying the original list also modified the shallow copied list because they share the same elements.

Deep Copy:
A deep copy of an object creates a new object and then recursively adds the copies of the child objects found in the original object. This means that:

- The new object is a separate entity from the original object.
- The elements of the new object are copies of the elements of the original object (i.e., they are not referenced).

Example:

import copy

original_list = [[1, 2], [3, 4]]
deep_copied_list = copy.deepcopy(original_list)

# Modify the original list
original_list[0][0] = 'X'

print(original_list)  # Output: [['X', 2], [3, 4]]
print(deep_copied_list)  # Output: [[1, 2], [3, 4]]

# As you can see, modifying the original list did not modify the deep copied list because they have separate elements.

# In summary:

# - Shallow copy: New object, same elements (references).
# - Deep copy: New object, new elements (copies).

In [ ]:
#4.Generate a 3*3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

##Ans.Here is the code to generate a 3x3 array with random floating-point numbers between 5 and 20, and then round each number in the array to 2 decimal places:


import numpy as np

# Generate a 3x3 array with random floating-point numbers between 5 and 20
array = np.random.uniform(5, 20, (3, 3))

# Round each number in the array to 2 decimal places
rounded_array = np.round(array, 2)

print(rounded_array)


Here's an example output:


[[12.15 18.92  5.78]
 [ 7.39 19.45 14.95]
 [17.18  6.51 13.29]]


Note that the actual output will vary each time you run the code, since it's generating random numbers.

In [ ]:
#5.Create a NumPy array with random integers between 1 and 10 of shape (5,6 ). After creating the array perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from arrayX

##Ans.Creating the NumPy array:


import numpy as np

# Create a NumPy array with random integers between 1 and 10 of shape (5,6)
array = np.random.randint(1, 11, (5, 6))

print("Original Array:")
print(array)


a) Extract all even integers from the array:


even_integers = array[array % 2 == 0]
print("\nEven Integers:")
print(even_integers)


b) Extract all odd integers from the array:


odd_integers = array[array % 2 != 0]
print("\nOdd Integers:")
print(odd_integers)


Here's an example output:


Original Array:
[[ 9  5  8  3  4  1]
 [10  7  2  9  5  6]
 [ 1  8  3  4  7  2]
 [ 6  5  9  1  8  3]
 [ 4  2  6 10  9  8]]

Even Integers:
[ 8  4 10  2  6  2  4  6  2  6 10  8  4  2  6  8]

Odd Integers:
[ 9  5  3  1  7  9  5  1  8  3  7  9  1  3  5  9]


Note that the actual output will vary each time you run the code, since it's generating random numbers.

In [ ]:
#6.Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform element-wise multiplication of between both array.

 ##Ans.Here is the code to create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10, find the indices of the maximum values along each depth level, and perform element-wise multiplication between two arrays:


import numpy as np

# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array1 = np.random.randint(1, 11, (3, 3, 3))
array2 = np.random.randint(1, 11, (3, 3, 3))

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array1, axis=2)
print("\nIndices of Maximum Values in Array 1:")
print(max_indices)

# b) Perform element-wise multiplication between both arrays
result = np.multiply(array1, array2)
print("\nElement-wise Multiplication Result:")
print(result)


Here's an example output:


Array 1:
[[[ 9  5  8]
  [ 3  1  6]
  [ 7  4  2]]

 [[ 5  9  3]
  [ 8  2 10]
  [ 1  6  9]]

 [[10  8  4]
  [ 2  7  5]
  [ 3  9  1]]]

Array 2:
[[[ 2  8  9]
  [ 5  3  1]
  [10  6  4]]

 [[ 9  1  7]
  [ 4  5  3]
  [ 2  8  6]]

 [[ 6  3  5]
  [ 1  9  2]
  [ 8  4 10]]]

Indices of Maximum Values in Array 1:
[[0 2 0]
 [1 2 2]
 [0 1 1]]

Element-wise Multiplication Result:
[[[18 40 72]
  [15  3  6]
  [70 24  8]]

 [[45  9 21]
  [32 10 30]
  [ 2 48 54]]

 [[60 24 20]
  [ 2 63 10]
  [24 36 10]]]


Note that the actual output will vary each time you run the code, since it's generating random numbers.

In [2]:
import pandas as pd

In [3]:
#7.Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

##Ans.

data = pd.read_csv("People Data.csv")

In [4]:
data

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Index          1000 non-null   int64 
 1   User Id        1000 non-null   object
 2   First Name     1000 non-null   object
 3   Last Name      1000 non-null   object
 4   Gender         1000 non-null   object
 5   Email          1000 non-null   object
 6   Phone          979 non-null    object
 7   Date of birth  1000 non-null   object
 8   Job Title      1000 non-null   object
 9   Salary         1000 non-null   int64 
dtypes: int64(2), object(8)
memory usage: 46.9+ KB


In [6]:
data.dtypes

Index             int64
User Id          object
First Name       object
Last Name        object
Gender           object
Email            object
Phone            object
Date of birth    object
Job Title        object
Salary            int64
dtype: object

In [7]:
data = pd.read_csv("People Data.csv", usecols = ["Phone"])

In [8]:
data

Phone
0             857.139.8239
1                      NaN
2            (599)782-0605
3                      NaN
4       (390)417-1635x3010
..                     ...
995           021.775.2933
996   001-149-710-7799x721
997  +1-750-774-4128x33265
998          (915)292-2254
999     079.752.5424x67259

[1000 rows x 1 columns]

In [9]:
df = pd.DataFrame(data)

In [10]:
df

Phone
0             857.139.8239
1                      NaN
2            (599)782-0605
3                      NaN
4       (390)417-1635x3010
..                     ...
995           021.775.2933
996   001-149-710-7799x721
997  +1-750-774-4128x33265
998          (915)292-2254
999     079.752.5424x67259

[1000 rows x 1 columns]

In [11]:
# Display original data types
print("Original Data Types:")
print(df.dtypes)

Original Data Types:
Phone    object
dtype: object


In [13]:
# Clean and transform the 'Phone' column
df['Phone'] = df['Phone'].str.replace(r'\D', '', regex = True)


In [14]:
df

Phone
0          8571398239
1                 NaN
2          5997820605
3                 NaN
4      39041716353010
..                ...
995        0217752933
996  0011497107799721
997  1750774412833265
998        9152922254
999   079752542467259

[1000 rows x 1 columns]

In [15]:
df.dtypes

Phone    object
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Phone   979 non-null    object
dtypes: object(1)
memory usage: 4.0+ KB


In [17]:
# Display cleaned data
print("\nCleaned Data:")
print(df)


Cleaned Data:
                Phone
0          8571398239
1                 NaN
2          5997820605
3                 NaN
4      39041716353010
..                ...
995        0217752933
996  0011497107799721
997  1750774412833265
998        9152922254
999   079752542467259

[1000 rows x 1 columns]


In [18]:
# Display updated data types
print("\nUpdated Data Types:")
print(df.dtypes)


Updated Data Types:
Phone    object
dtype: object


In [29]:
#8. Perform the following tasks using people dataset:
# a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
# c) Display the first 10 rows of the filtered dataset.
# d) Extract the ‘Salary’' column as a Series and display its last 5 values.

In [ ]:

##Ans.
#a)Read the 'People Data.csv' file using pandas, skipping the first 50 rows.

#Here's how you can read the 'People Data.csv' file using pandas, skipping the first 50 rows:


import pandas as pd

# Read the 'data.csv' file, skipping the first 50 rows
df = pd.read_csv('People Data.csv', skiprows=50)

# Display the first few rows of the dataframe
print(df.head())


#In this code:

#- pd.read_csv('People Data.csv') reads the 'data.csv' file into a pandas DataFrame.
# - skiprows=50 skips the first 50 rows of the file.
# - df.head() displays the first few rows of the DataFrame

In [30]:
df

50  afF3018e9cdd1dA     George    Mercer  Female  \
0      51  CccE5DAb6E288e5         Jo    Zavala    Male   
1      52  DfBDc3621D4bcec     Joshua     Carey  Female   
2      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
3      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
4      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..    ...              ...        ...       ...     ...   
945   996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
946   997  ECddaFEDdEc4FAB      Donna     Barry  Female   
947   998  2adde51d8B8979E      Cathy  Mckinney  Female   
948   999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
949  1000  8b756f6231DDC6e        Lee      Tran  Female   

    douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0           pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1      dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2      ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3     carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4     fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   
..                           ...                     ...         ...   
945       lyonsdaisy@example.net            021.775.2933  05-01-1959   
946      dariusbryan@example.com    001-149-710-7799x721  06-10-2001   
947       georgechan@example.org   +1-750-774-4128x33265  13-05-1918   
948          wanda04@example.net           (915)292-2254  31-08-1971   
949      deannablack@example.org      079.752.5424x67259  24-01-1947   

             Human resources officer   70000  
0                       Nurse, adult   80000  
1                Seismic interpreter   70000  
2                          Barrister   60000  
3               Engineer, structural  100000  
4                    Producer, radio   50000  
..                               ...     ...  
945                Personnel officer   90000  
946          Education administrator   50000  
947  Commercial/residential surveyor   60000  
948                 Ambulance person  100000  
949       Nurse, learning disability   90000  

[950 rows x 10 columns]

In [31]:
print(df.head())

   50  afF3018e9cdd1dA     George  Mercer  Female  \
0  51  CccE5DAb6E288e5         Jo  Zavala    Male   
1  52  DfBDc3621D4bcec     Joshua   Carey  Female   
2  53  f55b0A249f5E44D     Rickey   Hobbs  Female   
3  54  Ed71DcfaBFd0beE      Robyn  Reilly    Male   
4  55  FDaFD0c3f5387EC  Christina  Conrad    Male   

  douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0         pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1    dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2    ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3   carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4   fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   

  Human resources officer   70000  
0            Nurse, adult   80000  
1     Seismic interpreter   70000  
2               Barrister   60000  
3    Engineer, structural  100000  
4         Producer, radio   50000  


In [33]:
df = pd.read_csv('People Data.csv')

In [34]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [35]:
# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

#Here's how you can read only the specified columns from the 'People Data.csv' file:

df = pd.read_csv('People Data.csv', usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])


In [36]:
df

Last Name  Gender                          Email                  Phone  \
0     Mahoney    Male            pwarner@example.org           857.139.8239   
1      Rivers  Female  fergusonkatherine@example.net                    NaN   
2      Lowery  Female            fhoward@example.org          (599)782-0605   
3      Hooper    Male          zjohnston@example.com                    NaN   
4        Rice  Female               elin@example.net     (390)417-1635x3010   
..        ...     ...                            ...                    ...   
995    Bryant  Female         lyonsdaisy@example.net           021.775.2933   
996     Barry  Female        dariusbryan@example.com   001-149-710-7799x721   
997  Mckinney  Female         georgechan@example.org  +1-750-774-4128x33265   
998    Phelps    Male            wanda04@example.net          (915)292-2254   
999      Tran  Female        deannablack@example.org     079.752.5424x67259   

     Salary  
0     90000  
1     80000  
2     50000  
3     65000  
4    100000  
..      ...  
995   90000  
996   50000  
997   60000  
998  100000  
999   90000  

[1000 rows x 5 columns]

In [37]:
# Display the first few rows of the dataframe
print(df.head())


#In this code:

#- usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'] specifies the columns to read from the file.

  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000


In [39]:
# c) Display the first 10 rows of the filtered dataset.

#To display the first 10 rows of the filtered dataset, you can use the head() method:


# Display the first 10 rows of the filtered dataset
print(df.head(10))


#This will print the first 10 rows of the DataFrame df. If you want to display more or fewer rows, you can adjust the number inside the parentheses.

  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000
5  Caldwell    Male          kaitlin13@example.net          8537800927   50000
6   Hoffman    Male         jeffharvey@example.com   093.655.7480x7895   60000
7  Andersen    Male           alicia33@example.org          4709522945   65000
8      Mays    Male             jake50@example.com        013.820.4758   50000
9  Mitchell    Male      lanechristina@example.net  (560)903-5068x4985   50000


In [40]:
#Alternatively, you can use the iloc attribute to achieve the same result:


# Display the first 10 rows of the filtered dataset
print(df.iloc[:10])


#Both of these methods will display the first 10 rows of the filtered dataset.

  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000
5  Caldwell    Male          kaitlin13@example.net          8537800927   50000
6   Hoffman    Male         jeffharvey@example.com   093.655.7480x7895   60000
7  Andersen    Male           alicia33@example.org          4709522945   65000
8      Mays    Male             jake50@example.com        013.820.4758   50000
9  Mitchell    Male      lanechristina@example.net  (560)903-5068x4985   50000


In [42]:
# d) Extract the ‘Salary’' column as a Series and display its last 5 values.

#To extract the 'Salary' column as a Series and display its last 5 values, you can use the following code:


# Extract the 'Salary' column as a Series
salary_series = df['Salary']

# Display the last 5 values of the 'Salary' Series
print(salary_series.tail(5))


#In this code:

#- df['Salary'] extracts the 'Salary' column as a Series.
#- tail(5) returns the last 5 values of the Series.

#This will print the last 5 values of the 'Salary' Series. If you want to display more or fewer values, you can adjust the number inside the parentheses.

995     90000
996     50000
997     60000
998    100000
999     90000
Name: Salary, dtype: int64


In [43]:
#9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and 'Salary' should be less than 85000.

##Ans.To filter and select rows from the People_Data where the "Last Name" column contains the name 'Duke', 'Gender' column contains the word Female, and 'Salary' is less than 85000, you can use the following code:


# Filter and select rows based on conditions
filtered_data = df[(df['Last Name'] == 'Duke') & (df['Gender'] == 'Female') & (df['Salary'] < 85000)]

# Display the filtered data
print(filtered_data)


# In this code:

# - df['Last Name'] == 'Duke' filters rows where the "Last Name" column is 'Duke'.
# - df['Gender'] == 'Female' filters rows where the "Gender" column is 'Female'.
# - df['Salary'] < 85000 filters rows where the "Salary" column is less than 85000.
# - The & operator is used to combine the conditions with a logical AND.

# This will display the rows that match all the specified conditions.

    Last Name  Gender                     Email                   Phone  \
45       Duke  Female       diana26@example.net  001-366-475-8607x04350   
210      Duke  Female       robin78@example.com            740.434.0212   
457      Duke  Female  perryhoffman@example.org     +1-903-596-0995x489   
729      Duke  Female   kevinkramer@example.net            982.692.6257   

     Salary  
45    60000  
210   50000  
457   50000  
729   70000  


In [45]:
#10. Create a 7*5 Dataframe in pandas using a series generated from 35 random integers between 1 to 6?


##Ans.Here's how you can create a 7x5 DataFrame in pandas using a series generated from 35 random integers between 1 to 6:


import pandas as pd
import numpy as np

# Generate a series of 35 random integers between 1 to 6
random_series = pd.Series(np.random.randint(1, 7, 35))

# Reshape the series into a 7x5 DataFrame
df = random_series.values.reshape(7, 5)

# Create a DataFrame
df = pd.DataFrame(df)

print(df)


# In this code:

# - np.random.randint(1, 7, 35) generates an array of 35 random integers between 1 to 6.
# - pd.Series() converts the array into a pandas Series.
# - values.reshape(7, 5) reshapes the series into a 7x5 array.
# - pd.DataFrame() converts the array into a DataFrame.

# This will create a 7x5 DataFrame with random integers between 1 to 6.

   0  1  2  3  4
0  3  4  4  3  6
1  2  6  2  4  3
2  6  4  2  1  4
3  2  5  5  4  2
4  4  1  1  6  2
5  6  6  5  2  2
6  1  4  4  3  5


In [46]:
#11. Create two different Series, each of length 50, with the following criteria:
#a) The first Series should contain random numbers ranging from 10 to 50.
#b) The second Series should contain random numbers ranging from 100 to 1000.
#c) Create a DataFrame by 'joining these Series by column, and, change the names of the columns to 'col1', 'col2', etc.


##Ans.Here's how you can create the two Series and the DataFrame:


import pandas as pd
import numpy as np

# Create the first Series with random numbers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, 50))

# Create the second Series with random numbers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, 50))

# Create a DataFrame by joining the Series by column
df = pd.concat([series1, series2], axis=1)

# Change the names of the columns to 'col1', 'col2'
df.columns = ['col1', 'col2']

print(df)


# In this code:

# - np.random.randint(10, 51, 50) generates an array of 50 random integers between 10 and 50.
# - np.random.randint(100, 1001, 50) generates an array of 50 random integers between 100 and 1000.
# - pd.Series() converts the arrays into pandas Series.
# - pd.concat() joins the Series by column.
# - axis=1 specifies that the Series should be joined by column.
# - df.columns = ['col1', 'col2'] changes the names of the columns to 'col1' and 'col2'.

# This will create a DataFrame with two columns, 'col1' and 'col2', each containing 50 random numbers within the specified ranges.

    col1  col2
0     50   996
1     32   559
2     41   135
3     15   298
4     23   472
5     22   427
6     13   100
7     13   702
8     13   515
9     35   948
10    37   216
11    17   189
12    17   272
13    25   674
14    36   220
15    23   165
16    25   310
17    40   335
18    32   730
19    44   611
20    41   894
21    50   914
22    14   562
23    42   539
24    14   436
25    25   621
26    11   115
27    36   194
28    14   938
29    34   418
30    14   167
31    29   609
32    44   662
33    20   329
34    34   869
35    46   622
36    19   240
37    47   372
38    33   228
39    38   550
40    32   478
41    30   879
42    17   788
43    41   958
44    40   358
45    25   838
46    20   696
47    49   348
48    33   191
49    37   312


In [47]:
# 12. Perform the following operations using people data set:
# a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
# b) Delete the rows containing any missing values.
# c) Print the final output also.


##Ans.Here's how you can perform the operations using the people dataset:


import pandas as pd

# Load the people dataset
df = pd.read_csv('People Data.csv')

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset
df = df.drop(['Email', 'Phone', 'Date of birth'], axis=1)

# b) Delete the rows containing any missing values
df = df.dropna(how='any')

# c) Print the final output
print(df)


# In this code:

# - pd.read_csv('people_data.csv') loads the people dataset from the CSV file.
# - df.drop(['Email', 'Phone', 'Date of birth'], axis=1) deletes the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
# - df.dropna(how='any') deletes the rows containing any missing values.
# - print(df) prints the final output.

# Note: Make sure to replace 'people_data.csv' with the actual path to your dataset file.

# Also, be aware that deleting rows with missing values might lead to loss of important information. You might want to consider imputing missing values instead, depending on your specific use case.

     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000

In [ ]:
# 13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:
# a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.
# b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.
# c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.
# d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.
# e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.
# f) Display a legend for the scatter plot, the horizontal line, and the vertical line.


##Ans.Here's how you can perform the tasks using Matplotlib and NumPy:


import matplotlib.pyplot as plt
import numpy as np

# Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot using x and y
plt.scatter(x, y, color='red', marker='o', label='Random Values')

# Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'
plt.axhline(y=0.5, color='black', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'
plt.axvline(x=0.5, color='black', linestyle=':', label='x = 0.5')

# Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Set the title of the plot as 'Advanced Scatter Plot of Random Values'
plt.title('Advanced Scatter Plot of Random Values')

# Display a legend for the scatter plot, the horizontal line, and the vertical line
plt.legend()

# Display the plot
plt.show()


# In this code:

# - np.random.rand(100) generates 100 random float values between 0 and 1 for x and y.
# - plt.scatter() creates the scatter plot.
# - plt.axhline() adds the horizontal line.
# - plt.axvline() adds the vertical line.
# - plt.xlabel() and plt.ylabel() label the axes.
# - plt.title() sets the title.
# - plt.legend() displays the legend.
# - plt.show() displays the plot.

In [ ]:
# 14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:
# a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity').
# b) Label the x-axis as 'Date'.
# c) Set the title of the plot as 'Temperature and Humidity Over Time'.


##Ans.Here's how you can create the time-series dataset and perform the tasks using Matplotlib:


import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create a time-series dataset in a Pandas DataFrame
date = pd.date_range(start='2022-01-01', end='2022-01-31')
temperature = np.random.uniform(20, 30, 31)
humidity = np.random.uniform(50, 90, 31)

df = pd.DataFrame({'Date': date, 'Temperature': temperature, 'Humidity': humidity})

# Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes
fig, ax1 = plt.subplots()
ax1.plot(df['Date'], df['Temperature'], color='red')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (°C)', color='red')
ax1.tick_params(axis='y', labelcolor='red')

ax2 = ax1.twinx()
ax2.plot(df['Date'], df['Humidity'], color='blue')
ax2.set_ylabel('Humidity (%)', color='blue')
ax2.tick_params(axis='y', labelcolor='blue')

# Set the title of the plot
plt.title('Temperature and Humidity Over Time')

# Display the plot
plt.show()


# In this code:

# - pd.date_range() generates a date range for the 'Date' column.
# - np.random.uniform() generates random values for the 'Temperature' and 'Humidity' columns.
# - pd.DataFrame() creates the DataFrame.
# - plt.subplots() creates a figure and axis object.
# - ax1.plot() plots the 'Temperature' data on the left y-axis.
# - ax1.set_xlabel() and ax1.set_ylabel() label the x-axis and left y-axis.
# - ax2 = ax1.twinx() creates a secondary y-axis for 'Humidity'.
# - ax2.plot() plots the 'Humidity' data on the right y-axis.
# - ax2.set_ylabel() labels the right y-axis.
# - plt.title() sets the title.
# - plt.show() displays the plot.

In [ ]:
# 15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:
# a) Plot a histogram of the data with 30 bins.
# b) Overlay a line plot representing the normal distribution's probability density function (PDF).
# c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.
# d) Set the title of the plot as 'Histogram with PDF Overlay'.


##Ans.Here's how you can create the NumPy array and perform the tasks using Matplotlib:


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm

# Create a NumPy array containing 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.5, label='Histogram')

# Overlay a line plot representing the normal distribution's probability density function (PDF)
x = np.linspace(min(data), max(data), 100)
plt.plot(x, norm.pdf(x, loc=0, scale=1), 'r-', label='Normal PDF')

# Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')

# Set the title of the plot
plt.title('Histogram with PDF Overlay')

# Display a legend
plt.legend()

# Display the plot
plt.show()


# In this code:

# - np.random.normal() generates 1000 samples from a normal distribution.
# - plt.hist() plots the histogram with 30 bins and normalized frequencies.
# - np.linspace() generates x values for the PDF plot.
# - norm.pdf() calculates the PDF values for the x values.
# - plt.plot() plots the PDF line.
# - plt.xlabel() and plt.ylabel() label the axes.
# - plt.title() sets the title.
# - plt.legend() displays a legend.
# - plt.show() displays the plot.

In [ ]:
#16. Set the title of the plot as 'Histogram with PDF Overlay'.


##Ans.Here is the updated code with the title set:


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm

# Create a NumPy array containing 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.5, label='Histogram')

# Overlay a line plot representing the normal distribution's probability density function (PDF)
x = np.linspace(min(data), max(data), 100)
plt.plot(x, norm.pdf(x, loc=0, scale=1), 'r-', label='Normal PDF')

# Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')

# Set the title of the plot
plt.title('Histogram with PDF Overlay')

# Display a legend
plt.legend()

# Display the plot
plt.show()


#Now, when you run this code, the plot will have the title "Histogram with PDF Overlay".

In [ ]:
#17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin(quadrants), add a legend , label the axes, and set the title as 'Quadrant-wise Scatter Plot'.  


##Ans. Here's the code to create the Seaborn scatter plot:


import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Create two random arrays
x = np.random.randn(100)
y = np.random.randn(100)

# Create a Seaborn scatter plot
plt.figure(figsize=(8, 8))
sns.scatterplot(x=x, y=y, hue=np.where((x > 0) & (y > 0), 'Q1', np.where((x < 0) & (y > 0), 'Q2', np.where((x < 0) & (y < 0), 'Q3', 'Q4'))), palette=['red', 'green', 'blue', 'yellow'])

# Add a legend
plt.legend(title='Quadrants', loc='upper right')

# Label the axes
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Set the title
plt.title('Quadrant-wise Scatter Plot')

# Show the plot
plt.show()


#This code creates a Seaborn scatter plot of two random arrays, colors points based on their position relative to the origin (quadrants), adds a legend, labels the axes, and sets the title as 'Quadrant-wise Scatter Plot'. The points are colored as follows:

#- Red: Q1 (x > 0, y > 0)
#- Green: Q2 (x < 0, y > 0)
#- Blue: Q3 (x < 0, y < 0)
#- Yellow: Q4 (x > 0, y < 0)


In [ ]:
#18.With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'


##Ans.Here is the code to plot a line chart of a sine wave function using Bokeh:


import numpy as np
from bokeh.plotting import figure, show

# Create a sine wave function
x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

# Create a Bokeh plot
p = figure(title='Sine Wave Function', 
           x_axis_label='x', 
           y_axis_label='sin(x)')

# Add grid lines
p.grid.grid_line_alpha = 0.3

# Plot the sine wave function
p.line(x, y, legend_label='sin(x)', line_width=2)

# Show the plot
show(p)


#This code creates a sine wave function using NumPy, then uses Bokeh to create a plot with a title, labeled axes, and grid lines. The sine wave function is plotted as a line, and the plot is displayed using the show() function.

In [ ]:
#19.Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'.



##Ans.Here is the code to generate a bar chart of randomly generated categorical data using Bokeh:


import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import HoverTool

# Generate random categorical data
categories = ['A', 'B', 'C', 'D', 'E']
values = np.random.randint(1, 100, 5)

# Create a Bokeh plot
p = figure(title='Random Categorical Bar Chart', 
           x_axis_label='Category', 
           y_axis_label='Value', 
           x_range=categories)

# Add hover tooltips
hover = HoverTool(tooltips=[("Category", "@x"), ("Value", "@top")])
p.add_tools(hover)

# Plot the bar chart
p.vbar(x=categories, top=values, width=0.5, 
       fill_color=['red' if val > 50 else 'blue' for val in values])

# Show the plot
show(p)


#This code generates random categorical data, creates a Bokeh plot with a title, labeled axes, and hover tooltips, and plots a bar chart with bars colored based on their values. The plot is displayed using the show() function.

In [ ]:
#20.Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.


##Ans.Here is the code to create a basic line plot using Plotly:


import plotly.graph_objects as go
import numpy as np

# Generate random dataset
x = np.linspace(0, 10, 100)
y = np.random.uniform(0, 10, 100)

# Create a Plotly figure
fig = go.Figure(data=[go.Scatter(x=x, y=y)])

# Label the axes and set the title
fig.update_layout(
    title='Simple Line Plot',
    xaxis_title='X Axis',
    yaxis_title='Y Axis'
)

# Show the plot
fig.show()


# This code generates a random dataset, creates a Plotly figure with a line plot, labels the axes, and sets the title. The plot is displayed using the show() method.

# You can also customize the appearance of the plot by using various options available in the update_layout() method, such as changing the font size, color scheme, and more.

In [ ]:
#21.Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.


##Ans.Here is the code to create an interactive pie chart using Plotly:


import plotly.graph_objects as go
import numpy as np

# Generate random data
labels = ['A', 'B', 'C', 'D', 'E']
values = np.random.randint(1, 100, 5)

# Create a Plotly figure
fig = go.Figure(data=[go.Pie(labels=labels, values=values, textinfo='label+percent')])

# Set the title
fig.update_layout(title='Interactive Pie Chart')

# Show the plot
fig.show()


# This code generates random data, creates a Plotly figure with a pie chart, adds labels and percentages, and sets the title. The plot is displayed using the show() method.

# You can customize the appearance of the plot by using various options available in the update_layout() method, such as changing the font size, color scheme, and more. The pie chart is interactive, allowing you to hover over each slice to see the exact value and percentage.